### ISSUE TITLE
Install nunjucks inside of plugin folder [enhancement].

### ISSUE THREAD

**Issue by rludgero** [denkwerk/grunt-nunjuckr#2]
Hi @mariusbuescher,
a small suggestion for improving the plugin, i have noticed that when installed, **nunjucks** is installed at the **root** of the **node_modules** folder rather than installed inside of **nunjuckr** folder, would be nice for future versions to do with it is installed into nunjuckr folder.

Regards.

**Comment by mariusbuescher** [comment]
Hi @Rodrigo-Ludgero,
here at @denkwerk we use **grunt-nunjuckr** for prototyping and **nunjucks** for frontend templating. In production we precompile those templates with **grunt-nunjucks**. I defined **nunjucks** as a `peerDependency` to make **grunt-nunjucks** and **grunt-nunjuckr** use the **_same**_ version of **nunjucks**.

This change happened in `v1.1.0`. You can use `v1.0.0` instead to archive this behaviour. Make sure to lock your version in the `package.json` file to at least the minor Version either by using the `~` prefix or do not use any prefix at all to lock **grunt-nunjuckr** to this specific version.

I consider this issue closed for the reasons mentioned above.

Cheers
